services:
  - type: web
    name: jltv-avod-alpha12
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:gunicorn_app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///site.db
